
const products = [

    {
        id: 1,
        category: "Chudi",
        price: 100,
        prod_image: "../images/111.jpg",
        name: "From delhi",
    },
    {
        id: 2,
        category: "Lehanga",
        price: 199,
        prod_image: "../images/112.jpg",
        name: "From Mumbai",
        gender: "boys"
    },
    { id: 3,
         category: "Kurta Sets",
          price: 299,
          prod_image:"../images/113.jpg",
           name: "From Tamilnadu",
            gender: "girls" },
    { id: 4,
         category: "Lehanga",
          price: 399, 
          prod_image: "../images/114.jpg",
           name: "From Dubai",
            gender: "boys" },
    { id: 5,
         category: "Kurta Sets",
          price: 499,
           prod_image: "../images/115.jpg",
            name: "From Kerala",
             gender: "girls" },
    { id: 6,
         category: "Kurtas",
          price: 599, 
          prod_image: "../images/1.jpg",
           name: "From Mumbai",
            gender: "boys" },
    { id: 7,
         category: "Kurta Sets",
          price: 699, 
          prod_image: "../images/2.jpg",
           name: "From Tamilnadu",
            gender: "girls" },
    { id: 8, 
        category: "Kurtas",
         price: 799,
          prod_image: "../images/3.jpg",
           name: "From Dubai",
            gender: "boys" },
    { id: 9,
         category: "Kurtas",
          price: 899,
           prod_image: "../images/4.jpg", 
           name: "From Kerala",
            gender: "girls" },
    { id: 10,
         category: "Lehanga",
          price: 999, 
          prod_image: "../images/5.jpg",
           name: "From Mumbai",
            gender: "boys" },
    { id: 12,
         category: "Kurta Sets", 
         price: 199,
          prod_image: "../images/6.jpg",
           name: "From Tamilnadu", 
           gender: "boys" },
    { id: 13,
         category: "Lehanga", 
         price: 699,
          prod_image: "../images/7.jpg",
           name: "From Dubai",
            gender: "girls" },
    { id: 14,
         category: "Kurtas",
          price: 599, 
          prod_image: "../images/8.jpg",
           name: "From Kerala",
            gender: "girls" },
    { id: 15,
        category: "Kurtas",
        price: 199,
         prod_image: "../images/9.jpg",
          name: "From Mumbai",
           gender: "boys" },
    { id: 16,
         category: "Kurta Sets",
          price: 899,
           prod_image: "../images/10.jpg",
            name: "From Tamilnadu",
             gender: "boys" },
    { id: 17,
         category: "Kurta Sets",
          price: 699,
           prod_image: "../images/11.jpg",
            name: "From Dubai",
             gender: "girls" },
    { id: 18, 
        category: "Clothing sets",
         price: 599,
          prod_image: "../images/12.jpg",
           name: "From Kerala", 
           gender: "boys" },
    { id: 19, 
        category: "Lehangap",
         price: 799, 
         prod_image: "../images/13.jpg",
          name: "From Mumbai", 
          gender: "boys" },
    { id: 20, 
        category: "Kurta",
         price: 899, 
         prod_image: "../images/14.jpg", 
         name: "From Tamilnadu",
          gender: "boys" },
    { id: 21,
         category: "Kurta Sets",
          price: 699, 
          prod_image: "../images/15.jpg", 
          name: "From Dubai", 
          gender: "girls" },
    { id: 22,
         category: "Clothing sets",
          price: 599,
           prod_image: "../images/16.jpg",
            name: "From Kerala", 
            gender: "boys" },
    { id: 23, 
        category: "Kurtas", 
        price: 799,
         prod_image: "../images/17.jpg",
          name: "From Mumbai", 
          gender: "boys" },
    { id: 24,
         category: "Kurta", 
         price: 899, 
         prod_image: "../images/18.jpg",
          name: "From Tamilnadu",
           gender: "girls" },
    { id: 25, 
        category: "Clothing sets",
         price: 699,
          prod_image: "../images/19.jpg",
           name: "From Dubai",
            gender: "girls" },
    { id: 26,
         category: "Clothing sets",
          price: 599,
           prod_image: "../images/20.jpg",
            name: "From Kerala",
             gender: "boys" },
    { id: 27,
         category: "Clothing sets",
          price: 799,
           prod_image: "../images/21.jpg",
            name: "From Mumbai", 
            gender: "girls" },
    { id: 28,
         category: "Kurta", 
         price: 899,
         prod_image: "../images/22.jpg",
          name: "From Tamilnadu", 
          gender: "girls" },
    { id: 29,
        category: "Shall",
         price: 699,
          prod_image: "../images/23.jpg",
           name: "From Dubai", 
           gender: "boys" },
    { id: 30,
         category: "Shall",
          price: 599,
           prod_image: "../images/24.jpg",
            name: "From Kerala", 
            gender: "boys" },
    { id: 31,
         category: "Shall",
          price: 799,
           prod_image: "../images/25.jpg",
            name: "From Mumbai", 
            gender: "boys" },
    { id: 32, 
        category: "Kurta",
         price: 899, 
         prod_image: "../images/26.jpg",
          name: "From Tamilnadu", 
          gender: "girls" },
    { id: 34,
         category: "Sherwani",
          price: 699,
           prod_image: "../images/27.jpg", 
           name: "From Dubai",
            gender: "boys" },
    { id: 33,
         category: "Shall",
          price: 599, 
          prod_image: "../images/28.jpg",
           name: "From Kerala", 
           gender: "girls" },
    { id: 34,
         category: "Shall",
          price: 799, 
          prod_image: "../images/112.jpg",
           name: "From Mumbai",
            gender: "boys" },
    { id: 35,
         category: "Lehanga",
          price: 899,
           prod_image: "../images/113.jpg",
           name: "From Tamilnadu", 
           gender: "girls" },
    { id: 36, 
        category: "Sherwani",
         price: 699,
          prod_image: "../images/114.jpg",
           name: "From Dubai",
            gender: "boys" },
    { id: 37, 
        category: "Shall",
         price: 599,
          prod_image: "../images/115.jpg",
           name: "From Kerala",
            gender: "boys" },
    { id: 38, 
        category: "Sherwani",
         price: 799,
          prod_image: "../images/112.jpg",
           name: "From Mumbai",
            gender: "boys" },
    { id: 39,
         category: "Kurta",
          price: 899,
           prod_image: "../images/113.jpg", 
           name: "From Tamilnadu",
            gender: "boys" },
    { id: 30,
         category: "Sherwani",
          price: 699,
           prod_image: "../images/114.jpg", 
           name: "From Dubai",
            gender: "boys" },
    { id: 41,
         category: "Sherwani",
          price: 599, 
          prod_image: "../images/115.jpg", 
          name: "From Kerala",
           gender: "boys" },
    { id: 42, 
        category: "Sherwani", 
        price: 799,
         prod_image: "../images/112.jpg", 
         name: "From Mumbai",
          gender: "boys" },
    { id: 43,
         category: "Kurta",
          price: 899, 
          prod_image: "../images/113.jpg", 
          name: "From Tamilnadu",
           gender: "boys" },
    { id: 44,
         category: "Lehanga",
          price: 699, 
          prod_image: "../images/114.jpg", 
          name: "From Dubai", 
          gender: "boys" },
    { id: 45,
         category: "Shall", 
         price: 599,
          prod_image: "../images/115.jpg", 
          name: "From Kerala", 
          gender: "boys" },
    { id: 46,
         category: "Kurtas", 
         price: 599,
          prod_image: "../images/1.jpg", 
          name: "From Mumbai",
           gender: "boys" },
    { id: 47,
         category: "Kurta Sets", 
         price: 699,
          prod_image: "../images/2.jpg",
           name: "From Tamilnadu",
            gender: "girls" },
    { id: 48,
         category: "Kurtas",
          price: 799, 
          prod_image: "../images/3.jpg", 
          name: "From Dubai",
           gender: "boys" },
    { id: 49,
         category: "Kurtas",
          price: 899,
           prod_image: "../images/4.jpg", 
           name: "From Kerala",
            gender: "girls" },
    { id: 50,
         category: "Lehanga", 
         price: 999,
          prod_image: "../images/5.jpg",
           name: "From Mumbai",
            gender: "boys" },

];
export default products;